#!/data/data/com.termux/files/usr/bin/bash

# --SETTINGS--
Instances=2
Rejoin=true
RejoinTime=5
StartupTime=10
RobloxPackSuffixes="b c d"
VipServerUrl="https://www.roblox.com/share?code=YOUR_CODE_HERE&type=Server"
BasePackageName="com.roblox.clien"

#-----------------------------------------------------------------------
# KET THUC PHAN CAU HINH
#-----------------------------------------------------------------------

declare -a FullRobloxPackages=()

generateFullPackageNames() {
    local suffixes_array=($RobloxPackSuffixes)
    for suffix in "${suffixes_array[@]}"; do
        if [[ -n "$suffix" ]]; then
            FullRobloxPackages+=("${BasePackageName}${suffix}")
        fi
    done
    if [ ${#FullRobloxPackages[@]} -eq 0 ]; then
        exit 1
    fi
}

checkPackageExists() {
    pm list packages | grep -q "$1"
}

isRunning() {
    pidof "$1" > /dev/null 2>&1
}

openRobloxInstance() {
    local selectedClient="$1"
    if ! checkPackageExists "$selectedClient"; then
        return 1
    fi

    if isRunning "$selectedClient"; then
        : # Da dang chay, khong lam gi them
    else
        am start -a android.intent.action.VIEW -d "$VipServerUrl" -p "$selectedClient"
        sleep "$StartupTime"
    fi
}

forceCloseAllInstances() {
    local countToManage=$Instances
    if ((${#FullRobloxPackages[@]} < Instances)); then
        countToManage=${#FullRobloxPackages[@]}
    fi

    for ((i=0; i<countToManage; i++)); do
        local package_to_close="${FullRobloxPackages[$i]}"
        if checkPackageExists "$package_to_close"; then
            if isRunning "$package_to_close"; then
                su -c "am force-stop $package_to_close"
            fi
        fi
    done
    sleep 3
}

runInstances() {
    local opened_count=0
    local attempted_count=0
    
    for ((i=0; i<${#FullRobloxPackages[@]}; i++)); do
        if ((opened_count >= Instances)); then
            break
        fi
        
        ((attempted_count++))
        openRobloxInstance "${FullRobloxPackages[$i]}"
        ((opened_count++)) 
    done
}

continuousRejoinLoop() {
    local rejoin_time_seconds=$((RejoinTime * 60))

    if ((rejoin_time_seconds <= 0)); then
        exit 1
    fi

    while true; do
        forceCloseAllInstances
        runInstances
        
        local slept_time=0
        while ((slept_time < rejoin_time_seconds)); do
            local remaining_sleep=$((rejoin_time_seconds - slept_time))
            local sleep_chunk=60
            
            if ((remaining_sleep < sleep_chunk)); then
                sleep_chunk=$remaining_sleep
            fi
            
            if ((sleep_chunk <=0)); then 
                break 
            fi
            sleep $sleep_chunk
            slept_time=$((slept_time + sleep_chunk))
        done
    done
}

# Kiem tra cau hinh
if ! [[ "$Instances" =~ ^[1-9][0-9]*$ ]] || (( Instances <= 0 )); then
    exit 1
fi

if [[ "$Rejoin" != "true" ]] && [[ "$Rejoin" != "false" ]]; then
    exit 1
fi

if [[ "$Rejoin" == "true" ]]; then
    if ! [[ "$RejoinTime" =~ ^[1-9][0-9]*$ ]] || (( RejoinTime <= 0 )); then
        exit 1
    fi
fi

if ! [[ "$StartupTime" =~ ^[0-9]+$ ]] || (( StartupTime < 0 )); then
    exit 1
fi

if [[ -z "$RobloxPackSuffixes" ]]; then
    exit 1
fi

if [[ -z "$VipServerUrl" ]] || [[ "$VipServerUrl" == "https://www.roblox.com/share?code=YOUR_CODE_HERE&type=Server" ]]; then
    exit 1 # Thoat neu URL la gia tri mac dinh
fi

generateFullPackageNames # Ham nay se exit 1 neu khong co hau to hop le

# Kiem tra quyen root
if [[ $(id -u) -ne 0 ]]; then
    exit 1 # Thoat neu khong co quyen root, vi 'su -c' se duoc goi
fi

# Chay logic chinh
if [[ "$Rejoin" == "true" ]]; then
    continuousRejoinLoop
else
    forceCloseAllInstances
    runInstances
fi

exit 0
